<?php

namespace AppBundle\Repository;

/**
 * jobOffersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class jobOffersRepository extends \Doctrine\ORM\EntityRepository
{
}
